<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Configuracao extends Model
{
    use HasFactory;

    protected $table = 'configuracoes';

    protected $fillable = [
        'empresa_id',
        'apiUrl',
        'apiRefreshInterval',
        'videoUrl',
        'videoMuted',
        'videoPlaylist',
        'showVideoPanel',
        'priceColor',
        'offerColor',
        'rowBackgroundColor',
        'borderColor',
        'rowBorderWidth',
        'productsPanelBackgroundColor',
        'listBorderColor',
        'listBorderWidth',
        'videoBackgroundColor',
        'showRightSidebarPanel',
        'showRightSidebarLogo',
        'showLeftVerticalLogo',
        'rightSidebarLogoPosition',
        'rightSidebarLogoPositionWindows',
        'rightSidebarLogoPositionAndroid',
        'rightSidebarLogoUrl',
        'leftVerticalLogoUrl',
        'leftVerticalLogoWidth',
        'leftVerticalLogoHeight',
        'leftVerticalLogoWidthWindows',
        'leftVerticalLogoHeightWindows',
        'leftVerticalLogoWidthAndroid',
        'leftVerticalLogoHeightAndroid',
        'rightSidebarLogoWidth',
        'rightSidebarLogoHeight',
        'rightSidebarLogoWidthWindows',
        'rightSidebarLogoHeightWindows',
        'rightSidebarLogoWidthAndroid',
        'rightSidebarLogoHeightAndroid',
        'rightSidebarLogoBackgroundColor',
        'isRightSidebarLogoBackgroundTransparent',
        'showRightSidebarBorder',
        'rightSidebarBorderColor',
        'rightSidebarBorderWidth',
        'rightSidebarMediaType',
        'rightSidebarGlobalGalleryCode',
        'rightSidebarImageUrls',
        'fullScreenSlideImageUrls',
        'fullScreenSlideInterval',
        'fullScreenSlideReturnDelaySeconds',
        'fullScreenSlideEnabled',
        'fullScreenSlideStartDate',
        'fullScreenSlideEndDate',
        'fullScreenSlideEnabledWindows',
        'fullScreenSlideEnabledAndroid',
        'fullScreenSlideImageWidthWindows',
        'fullScreenSlideImageHeightWindows',
        'fullScreenSlideImageWidthAndroid',
        'fullScreenSlideImageHeightAndroid',
        'rightSidebarImageSchedules',
        'rightSidebarImageInterval',
        'rightSidebarImageFit',
        'rightSidebarHybridVideoDuration',
        'rightSidebarHybridImageDuration',
        'rightSidebarProductCarouselEnabled',
        'rightSidebarProductDisplayMode',
        'rightSidebarProductTransitionMode',
        'rightSidebarPlaybackSequence',
        'rightSidebarProductInterval',
        'rightSidebarProductShowImage',
        'rightSidebarProductImageWidth',
        'rightSidebarProductImageHeight',
        'rightSidebarProductShowName',
        'rightSidebarProductShowPrice',
        'rightSidebarProductNamePosition',
        'rightSidebarProductPricePosition',
        'rightSidebarProductNameColor',
        'rightSidebarProductPriceColor',
        'rightSidebarProductNameBadgeEnabled',
        'rightSidebarProductNameBadgeColor',
        'rightSidebarProductPriceBadgeEnabled',
        'rightSidebarProductPriceBadgeColor',
        'productListType',
        'productListLeftGroupIds',
        'productListRightGroupIds',
        'productListOrderMode',
        'productAlphabeticalDirection',
        'productDepartmentOrder',
        'productGroupOrder',
        'isVideoPanelTransparent',
        'appBackgroundColor',
        'mainBorderColor',
        'mainBorderWidth',
        'gradientStartColor',
        'gradientEndColor',
        'backgroundImageUrl',
        'useGradient',
        'gradientStop1',
        'gradientStop2',
        'showBorder',
        'isRowBorderTransparent',
        'showTitle',
        'titleText',
        'isTitleDynamic',
        'titlePosition',
        'titleFontSize',
        'titleFontFamily',
        'titleTextColor',
        'titleBackgroundColor',
        'isTitleBackgroundTransparent',
        'showTitleBorder',
        'showBackgroundImage',
        'isProductsPanelTransparent',
        'isListBorderTransparent',
        'isMainBorderEnabled',
        'isRoundedCornersEnabled',
        'isRowRoundedEnabled',
        'showImage',
        'imageSize',
        'imageWidth',
        'imageHeight',
        'rowVerticalPadding',
        'rowLineSpacing',
        'productListVerticalOffset',
        'rightSidebarImageHeight',
        'rightSidebarImageWidth',
        'rightSidebarAndroidHeight',
        'rightSidebarAndroidWidth',
        'rightSidebarAndroidHorizontalOffset',
        'rightSidebarAndroidRightMargin',
        'rightSidebarAndroidVerticalOffset',
        'listFontSize',
        'groupLabelFontSize',
        'groupLabelVerticalOffset',
        'groupLabelFontFamily',
        'groupLabelColor',
        'showGroupLabelBadge',
        'groupLabelBadgeColor',
        'offerSlideEnabled',
        'offerSlideIntervalSeconds',
        'offerSlideDescriptionFontFamily',
        'offerSlideDescriptionFontSize',
        'offerSlideDescriptionColor',
        'offerSlideDescriptionPosition',
        'offerSlideDescriptionOffsetY',
        'offerSlideDescriptionOffsetX',
        'offerSlideDescriptionBorderEnabled',
        'offerSlideDescriptionBorderColor',
        'offerSlideDescriptionBorderWidth',
        'offerSlideBackgroundColorStart',
        'offerSlideBackgroundColorEnd',
        'offerSlideBackgroundTransparent',
        'offerSlideBackgroundImageUrl',
        'offerSlideBackgroundImageFullScreen',
        'offerSlideBackgroundImageWidth',
        'offerSlideBackgroundImageHeight',
        'offerSlideBackgroundImageMarginTop',
        'offerSlideBackgroundImageMarginBottom',
        'offerSlideSingleItemProductImageEnabled',
        'offerSlideSingleItemProductImageWidth',
        'offerSlideSingleItemProductImageHeight',
        'offerSlideSingleItemProductImageTop',
        'offerSlideSingleItemProductImageRight',
        'offerSlideSingleItemProductImageSide',
        'offerSlideSingleItemProductImageVerticalPosition',
        'offerSlideSingleItemProductImageBorderEnabled',
        'offerSlideSingleItemProductImageBorderColor',
        'offerSlideSingleItemProductImageBorderWidth',
        'offerSlideTitleEnabled',
        'offerSlideTitleText',
        'offerSlideTitleColor',
        'offerSlideTitleFontSize',
        'offerSlideTitleFontFamily',
        'offerSlideTitleAlignment',
        'offerSlideLayoutMode',
        'offerSlideTestModeEnabled',
        'offerSlideSmoothTransitionEnabled',
        'offerSlideCardBackgroundColor',
        'offerSlideCardBackgroundColorStart',
        'offerSlideCardBackgroundColorEnd',
        'offerSlideCardBackgroundTransparent',
        'offerSlideCardBackgroundTransparencyPercent',
        'offerSlideCardBorderEnabled',
        'offerSlideCardBorderColor',
        'offerSlideCardBorderWidth',
        'offerSlideScreenBorderEnabled',
        'offerSlideScreenBorderColor',
        'offerSlideScreenBorderWidth',
        'offerSlidePriceFontFamily',
        'offerSlidePriceFontSize',
        'offerSlidePriceColor',
        'offerSlidePricePosition',
        'offerSlidePriceAlignment',
        'offerSlidePriceOffsetY',
        'offerSlidePriceOffsetX',
        'offerSlidePriceBorderEnabled',
        'offerSlidePriceBorderColor',
        'offerSlidePriceBorderWidth',
        'isPaginationEnabled',
        'pageSize',
        'paginationInterval',
    ];

    public function empresa()
    {
        return $this->belongsTo(Empresa::class);
    }

    protected $casts = [
        'useGradient' => 'boolean',
        'videoMuted' => 'boolean',
        'videoPlaylist' => 'array',
        'showVideoPanel' => 'boolean',
        'showRightSidebarPanel' => 'boolean',
        'showRightSidebarLogo' => 'boolean',
        'showLeftVerticalLogo' => 'boolean',
        'leftVerticalLogoWidth' => 'integer',
        'leftVerticalLogoHeight' => 'integer',
        'offerSlideTitleFontSize' => 'integer',
        'leftVerticalLogoWidthWindows' => 'integer',
        'leftVerticalLogoHeightWindows' => 'integer',
        'leftVerticalLogoWidthAndroid' => 'integer',
        'leftVerticalLogoHeightAndroid' => 'integer',
        'rightSidebarLogoWidth' => 'integer',
        'rightSidebarLogoHeight' => 'integer',
        'rightSidebarLogoWidthWindows' => 'integer',
        'rightSidebarLogoHeightWindows' => 'integer',
        'rightSidebarLogoWidthAndroid' => 'integer',
        'rightSidebarLogoHeightAndroid' => 'integer',
        'isRightSidebarLogoBackgroundTransparent' => 'boolean',
        'showRightSidebarBorder' => 'boolean',
        'productDepartmentOrder' => 'array',
        'productGroupOrder' => 'array',
        'productListLeftGroupIds' => 'array',
        'productListRightGroupIds' => 'array',
        'rightSidebarImageSchedules' => 'array',
        'showBorder' => 'boolean',
        'isRowBorderTransparent' => 'boolean',
        'showTitle' => 'boolean',
        'isTitleDynamic' => 'boolean',
        'isTitleBackgroundTransparent' => 'boolean',
        'showTitleBorder' => 'boolean',
        'showBackgroundImage' => 'boolean',
        'isProductsPanelTransparent' => 'boolean',
        'isListBorderTransparent' => 'boolean',
        'isVideoPanelTransparent' => 'boolean',
        'isMainBorderEnabled' => 'boolean',
        'isRoundedCornersEnabled' => 'boolean',
        'isRowRoundedEnabled' => 'boolean',
        'showImage' => 'boolean',
        'showGroupLabelBadge' => 'boolean',
        'offerSlideBackgroundTransparent' => 'boolean',
        'offerSlideBackgroundImageFullScreen' => 'boolean',
        'offerSlideSingleItemProductImageEnabled' => 'boolean',
        'offerSlideTitleEnabled' => 'boolean',
        'offerSlideTestModeEnabled' => 'boolean',
        'offerSlideSmoothTransitionEnabled' => 'boolean',
        'offerSlideCardBackgroundTransparent' => 'boolean',
        'isPaginationEnabled' => 'boolean',
        'gradientStop1' => 'float',
        'gradientStop2' => 'float',
        'apiRefreshInterval' => 'integer',
        'mainBorderWidth' => 'integer',
        'imageSize' => 'integer',
        'rowBorderWidth' => 'integer',
        'listBorderWidth' => 'integer',
        'rightSidebarBorderWidth' => 'integer',
        'rightSidebarImageInterval' => 'integer',
        'fullScreenSlideInterval' => 'integer',
        'fullScreenSlideReturnDelaySeconds' => 'integer',
        'fullScreenSlideEnabled' => 'boolean',
        'fullScreenSlideEnabledWindows' => 'boolean',
        'fullScreenSlideEnabledAndroid' => 'boolean',
        'fullScreenSlideImageWidthWindows' => 'integer',
        'fullScreenSlideImageHeightWindows' => 'integer',
        'fullScreenSlideImageWidthAndroid' => 'integer',
        'fullScreenSlideImageHeightAndroid' => 'integer',
        'rightSidebarImageHeight' => 'integer',
        'rightSidebarImageWidth' => 'integer',
        'rightSidebarAndroidHeight' => 'integer',
        'rightSidebarAndroidWidth' => 'integer',
        'rightSidebarAndroidHorizontalOffset' => 'integer',
        'rightSidebarAndroidRightMargin' => 'integer',
        'rightSidebarAndroidVerticalOffset' => 'integer',
        'rightSidebarHybridVideoDuration' => 'integer',
        'rightSidebarHybridImageDuration' => 'integer',
        'rightSidebarProductCarouselEnabled' => 'boolean',
        'rightSidebarProductInterval' => 'integer',
        'rightSidebarProductShowImage' => 'boolean',
        'rightSidebarProductImageWidth' => 'integer',
        'rightSidebarProductImageHeight' => 'integer',
        'rightSidebarProductShowName' => 'boolean',
        'rightSidebarProductShowPrice' => 'boolean',
        'rightSidebarProductNameBadgeEnabled' => 'boolean',
        'rightSidebarProductPriceBadgeEnabled' => 'boolean',
        'imageWidth' => 'integer',
        'imageHeight' => 'integer',
        'rowVerticalPadding' => 'integer',
        'rowLineSpacing' => 'integer',
        'productListVerticalOffset' => 'integer',
        'listFontSize' => 'integer',
        'groupLabelFontSize' => 'integer',
        'groupLabelVerticalOffset' => 'integer',
        'offerSlideEnabled' => 'boolean',
        'offerSlideIntervalSeconds' => 'integer',
        'offerSlideBackgroundImageWidth' => 'integer',
        'offerSlideBackgroundImageHeight' => 'integer',
        'offerSlideBackgroundImageMarginTop' => 'integer',
        'offerSlideBackgroundImageMarginBottom' => 'integer',
        'offerSlideSingleItemProductImageWidth' => 'integer',
        'offerSlideSingleItemProductImageHeight' => 'integer',
        'offerSlideSingleItemProductImageTop' => 'integer',
        'offerSlideSingleItemProductImageRight' => 'integer',
        'offerSlideSingleItemProductImageBorderEnabled' => 'boolean',
        'offerSlideCardBackgroundTransparencyPercent' => 'integer',
        'offerSlideCardBorderEnabled' => 'boolean',
        'offerSlideCardBorderWidth' => 'integer',
        'offerSlideScreenBorderEnabled' => 'boolean',
        'offerSlideScreenBorderWidth' => 'integer',
        'offerSlideDescriptionFontSize' => 'integer',
        'offerSlideDescriptionOffsetY' => 'integer',
        'offerSlideDescriptionOffsetX' => 'integer',
        'offerSlideDescriptionBorderEnabled' => 'boolean',
        'offerSlideDescriptionBorderWidth' => 'integer',
        'offerSlideTitleFontSize' => 'integer',
        'offerSlidePriceFontSize' => 'integer',
        'offerSlidePriceOffsetY' => 'integer',
        'offerSlidePriceOffsetX' => 'integer',
        'offerSlidePriceBorderEnabled' => 'boolean',
        'offerSlidePriceBorderWidth' => 'integer',
        'titleFontSize' => 'integer',
        'pageSize' => 'integer',
        'paginationInterval' => 'integer',
    ];
}
