<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Configuracao extends Model
{
    use HasFactory;

    protected $table = 'configuracoes';

    protected $fillable = [
        'empresa_id',
        'apiUrl',
        'apiRefreshInterval',
        'videoUrl',
        'videoMuted',
        'videoPlaylist',
        'showVideoPanel',
        'priceColor',
        'offerColor',
        'rowBackgroundColor',
        'borderColor',
        'rowBorderWidth',
        'productsPanelBackgroundColor',
        'listBorderColor',
        'listBorderWidth',
        'videoBackgroundColor',
        'showRightSidebarPanel',
        'showRightSidebarBorder',
        'rightSidebarBorderColor',
        'rightSidebarBorderWidth',
        'rightSidebarMediaType',
        'rightSidebarGlobalGalleryCode',
        'rightSidebarImageUrls',
        'rightSidebarImageInterval',
        'rightSidebarImageFit',
        'rightSidebarHybridVideoDuration',
        'rightSidebarHybridImageDuration',
        'productListType',
        'productListLeftGroupIds',
        'productListRightGroupIds',
        'productListOrderMode',
        'productAlphabeticalDirection',
        'productDepartmentOrder',
        'productGroupOrder',
        'isVideoPanelTransparent',
        'appBackgroundColor',
        'mainBorderColor',
        'mainBorderWidth',
        'gradientStartColor',
        'gradientEndColor',
        'backgroundImageUrl',
        'useGradient',
        'gradientStop1',
        'gradientStop2',
        'showBorder',
        'isRowBorderTransparent',
        'showTitle',
        'titleText',
        'isTitleDynamic',
        'titlePosition',
        'titleFontSize',
        'titleFontFamily',
        'titleTextColor',
        'titleBackgroundColor',
        'isTitleBackgroundTransparent',
        'showBackgroundImage',
        'isProductsPanelTransparent',
        'isListBorderTransparent',
        'isMainBorderEnabled',
        'isRoundedCornersEnabled',
        'isRowRoundedEnabled',
        'showImage',
        'imageSize',
        'imageWidth',
        'imageHeight',
        'rowVerticalPadding',
        'rightSidebarImageHeight',
        'rightSidebarImageWidth',
        'listFontSize',
        'groupLabelFontSize',
        'groupLabelFontFamily',
        'groupLabelColor',
        'showGroupLabelBadge',
        'groupLabelBadgeColor',
        'isPaginationEnabled',
        'pageSize',
        'paginationInterval',
    ];

    public function empresa()
    {
        return $this->belongsTo(Empresa::class);
    }

    protected $casts = [
        'useGradient' => 'boolean',
        'videoMuted' => 'boolean',
        'videoPlaylist' => 'array',
        'showVideoPanel' => 'boolean',
        'showRightSidebarPanel' => 'boolean',
        'showRightSidebarBorder' => 'boolean',
        'productDepartmentOrder' => 'array',
        'productGroupOrder' => 'array',
        'productListLeftGroupIds' => 'array',
        'productListRightGroupIds' => 'array',
        'showBorder' => 'boolean',
        'isRowBorderTransparent' => 'boolean',
        'showTitle' => 'boolean',
        'isTitleDynamic' => 'boolean',
        'isTitleBackgroundTransparent' => 'boolean',
        'showBackgroundImage' => 'boolean',
        'isProductsPanelTransparent' => 'boolean',
        'isListBorderTransparent' => 'boolean',
        'isVideoPanelTransparent' => 'boolean',
        'isMainBorderEnabled' => 'boolean',
        'isRoundedCornersEnabled' => 'boolean',
        'isRowRoundedEnabled' => 'boolean',
        'showImage' => 'boolean',
        'showGroupLabelBadge' => 'boolean',
        'isPaginationEnabled' => 'boolean',
        'gradientStop1' => 'float',
        'gradientStop2' => 'float',
        'apiRefreshInterval' => 'integer',
        'mainBorderWidth' => 'integer',
        'imageSize' => 'integer',
        'rowBorderWidth' => 'integer',
        'listBorderWidth' => 'integer',
        'rightSidebarBorderWidth' => 'integer',
        'rightSidebarImageInterval' => 'integer',
        'rightSidebarImageHeight' => 'integer',
        'rightSidebarImageWidth' => 'integer',
        'rightSidebarHybridVideoDuration' => 'integer',
        'rightSidebarHybridImageDuration' => 'integer',
        'imageWidth' => 'integer',
        'imageHeight' => 'integer',
        'rowVerticalPadding' => 'integer',
        'listFontSize' => 'integer',
        'groupLabelFontSize' => 'integer',
        'titleFontSize' => 'integer',
        'pageSize' => 'integer',
        'paginationInterval' => 'integer',
    ];
}
